Update 6.6合并一加.yml

diff --git a/.github/workflows/6.6合并一加.yml b/.github/workflows/6.6合并一加.yml
--- a/.github/workflows/6.6合并一加.yml
+++ b/.github/workflows/6.6合并一加.yml
@@ -310,6 +310,11 @@ jobs:
           export SOURCE_DATE_EPOCH=$(date -d "${{ github.event.inputs.BUILD_TIMESTAMP }}" +%s)
           echo "SOURCE_DATE_EPOCH=$SOURCE_DATE_EPOCH" >> $GITHUB_ENV
 
+      # - name: 8.2 拉取afdo
+      #   run: |
+      #     cd kernel_workspace/kernel_platform/
+      #     git clone https://github.com/PxxPei/afdo.git    
+
       - name: 9.1 安装和设置 Clang 19.0.0 编译器环境
         run: |
           mkdir -p clang19
@@ -330,19 +335,19 @@ jobs:
           export SOURCE_DATE_EPOCH=${{ env.SOURCE_DATE_EPOCH }}
           
           # 设置AFDO配置文件
-          export AFDO_PROFILE="${{ github.workspace }}/${{ env.WORKSPACE_DIR }}/afdo/kernel.afdo"
-          if [ ! -f "$AFDO_PROFILE" ]; then
-              echo "Error: AFDO profile not found at $AFDO_PROFILE"
-              exit 1
-          fi
+          # export AFDO_PROFILE="${{ github.workspace }}/${{ env.WORKSPACE_DIR }}/afdo/kernel.afdo"
+          # if [ ! -f "$AFDO_PROFILE" ]; then
+          #    echo "Error: AFDO profile not found at $AFDO_PROFILE"
+          #     exit 1
+          # fi
           
           echo "KERNEL_TIME = $KERNEL_TIME"
           echo "SOURCE_DATE_EPOCH = $SOURCE_DATE_EPOCH"
-          echo "Using KCFLAGS: -Wno-error -fauto-profile=$AFDO_PROFILE"
+          # echo "Using KCFLAGS: -Wno-error -fauto-profile=$AFDO_PROFILE"
           
           # 设置编译参数
           export CC="ccache clang"
-          export KCFLAGS="-Wno-error -fauto-profile=$AFDO_PROFILE"
+          # export KCFLAGS="-Wno-error -fauto-profile=$AFDO_PROFILE"
           export MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang \
           RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
           PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
