更新 ace5pro(娱乐自定义内核版本).yml

diff --git a/.github/workflows/ace5pro(娱乐自定义内核版本).yml b/.github/workflows/ace5pro(娱乐自定义内核版本).yml
--- a/.github/workflows/ace5pro(娱乐自定义内核版本).yml
+++ b/.github/workflows/ace5pro(娱乐自定义内核版本).yml
@@ -168,9 +168,15 @@ jobs:
           
       - name: Apply lz4kd Patches
         run: |
-          cd kernel_workspace/kernel_platform/common
-          cp ../../SukiSU_patch/other/lz4k_patch/${{ github.event.inputs.KERNEL_VERSION }}/lz4kd.patch ./
-          patch -p1 -F 3 < lz4kd.patch || true
+         set -e
+         cd kernel_workspace/kernel_platform/common
+         PATCH_FILE=../../SukiSU_patch/other/zram/zram_patch/${{ inputs.KERNEL_VERSION }}/lz4kd.patch
+         if [[ -f "$PATCH_FILE" ]]; then
+         cp "$PATCH_FILE" ./lz4kd.patch
+         patch -p1 -F 3 < lz4kd.patch || true
+         else
+         echo "❗ lz4kd patch not found for kernel version ${{ inputs.KERNEL_VERSION }}"
+         fi
            
       - name: Add SUSFS Configuration Settings
         run: |
@@ -212,6 +218,15 @@ jobs:
           cd common
           git add -A && git commit -a -m "BUILD Kernel"
 
+      - name: 启用LTO
+        if: ${{ fromJSON(github.event.inputs.ENABLE_LTO) }}
+        run: |
+         cd kernel_workspace/kernel_platform
+         echo "CONFIG_LTO_CLANG=y" >> ./common/arch/arm64/configs/gki_defconfig
+         echo "CONFIG_LTO_CLANG_THIN=y" >> ./common/arch/arm64/configs/gki_defconfig
+         sudo sed -i 's/check_defconfig//' ./common/build.config.gki
+         cd common
+         git add -A && git commit -a -m "BUILD Kernel with LTO enabled"
 
       - name: Add make name
         run: |
