更新 asd.yml

diff --git a/.github/workflows/asd.yml b/.github/workflows/asd.yml
--- a/.github/workflows/asd.yml
+++ b/.github/workflows/asd.yml
@@ -153,14 +153,14 @@ elif [ -d "/opt/android/sdk/ndk/" ]; then
             NDK_ROOT=$(find /opt/android/sdk/ndk/ -maxdepth 1 -type d -name "*-*" | head -n 1)
 fi
 
-if [ -n "${NDK_ROOT}" ]; then
-  export PATH="${NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin:${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin:${PATH}"
-  export CROSS_COMPILE_ARM64="${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-"
-  echo "Using NDK toolchain from: ${NDK_ROOT}"
+            if [ -n "${NDK_ROOT}" ]; then
+            export PATH="${NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin:${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin:${PATH}"
+            export CROSS_COMPILE_ARM64="${NDK_ROOT}/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-"
+            echo "Using NDK toolchain from: ${NDK_ROOT}"
 else
-  echo "Error: NDK toolchain not found in common locations."
-  exit 1
-fi
+            echo "Error: NDK toolchain not found in common locations."
+            exit 1
+           fi
 
           export ARCH=arm64
           export CROSS_COMPILE="${CROSS_COMPILE_ARM64}"
