Update optimized_workflow_final.yml

diff --git a/.github/workflows/optimized_workflow_final.yml b/.github/workflows/optimized_workflow_final.yml
--- a/.github/workflows/optimized_workflow_final.yml
+++ b/.github/workflows/optimized_workflow_final.yml
@@ -293,10 +293,10 @@ jobs:
       #    rm -rf ./sched_ext/.git
 
       # 拉取AFDO（AutoFDO）性能优化配置文件
-      - name: 拉取afdo
-        run: |
-          cd kernel_workspace/kernel_platform/
-          git clone https://github.com/PxxPei/afdo.git
+      #- name: 拉取afdo
+      #  run: |
+      #    cd kernel_workspace/kernel_platform/
+      #    git clone https://github.com/PxxPei/afdo.git
 
       # ========================================
       # 阶段九：构建时间戳设置
@@ -320,22 +320,22 @@ jobs:
           # 设置固定内核构建时间          
           export KERNEL_TIME="${{ github.event.inputs.BUILD_TIMESTAMP }}"
           export KBUILD_BUILD_TIMESTAMP="$KERNEL_TIME"
-          export SOURCE_DATE_EPOCH=$(date -d "$KERNEL_TIME" +%s)
+          # export SOURCE_DATE_EPOCH=$(date -d "$KERNEL_TIME" +%s)
           
           # 设置 AFDO 配置文件路径
-          export AFDO_PROFILE="${{ github.workspace }}/kernel_workspace/kernel_platform/afdo/kernel.afdo"
-          if [ ! -f "$AFDO_PROFILE" ]; then
-            echo "Error: AFDO profile not found at $AFDO_PROFILE"
-          exit 1
-          fi
+          # export AFDO_PROFILE="${{ github.workspace }}/kernel_workspace/kernel_platform/afdo/kernel.afdo"
+          # if [ ! -f "$AFDO_PROFILE" ]; then
+          #   echo "Error: AFDO profile not found at $AFDO_PROFILE"
+          # exit 1
+          # fi
           
           # 打印验证
           echo "KERNEL_TIME = $KERNEL_TIME"
           echo "SOURCE_DATE_EPOCH = $SOURCE_DATE_EPOCH"
-          echo "Using KCFLAGS: -Wno-error -fauto-profile=$AFDO_PROFILE"
+          # echo "Using KCFLAGS: -Wno-error -fauto-profile=$AFDO_PROFILE"
           
           # 设置一些通用参数（便于后续维护）
-          export KCFLAGS="-Wno-error -fauto-profile=$AFDO_PROFILE"
+          # export KCFLAGS="-Wno-error -fauto-profile=$AFDO_PROFILE"
           export MAKE_ARGS="LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang \
           RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc \
           PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole \
